name: gce_guide
description: An app made in Flutter which helps GCE students to access past
  papers (IGCSE, A/AS, O Levels).

publish_to: "none"
version: 0.0.6+6

environment:
  sdk: ">=2.19.0-219.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  html: ^0.15.1
  http: ^0.13.5
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
