name: "Android CI Actions"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*" # Ignore tags that start with "v" (e.g. v1.0.0) because they are handled by release-build.yml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v3
        with:
          java-version: "12"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Set up Flutter
        run: flutter pub get
      - name: Build with Flutter
        run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app-release.apk
